# Generated by Django 4.1 on 2022-10-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='origins',
            new_name='origin',
        ),
    ]
